apiVersion: v1
kind: Secret
metadata:
  name: dwhtrans-catalog-db
  labels:
    app.kubernetes.io/name: dwhtrans-catalog
    app.kubernetes.io/part-of: dwhtrans-catalog
    app.kubernetes.io/component: metastore
    exp.openshift.io/area: hive-catalog
type: Opaque
stringData:
  username: metastore
  password: change-me
